version: '3.8'

services:
  user_srv:
    build:
      context: ./backend/user_srv
    ports:
      - "50051:50051"
    volumes:
      - ./backend/files:/app/files
      - ./backend/images:/app/images
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  web:
    build:
      context: ./backend/web
    ports:
      - "8080:8080"
    volumes:
      - ./backend/files:/app/files
      - ./backend/images:/app/images
    depends_on:
      user_srv:
        condition: service_started
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: capstone
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    build: ./frontend
    ports:
      - "3333:3000" # mapping the external port 3333 to container's internal port 3000 (on your computer use localhost:3333)
    volumes: # every time you make a change, this will reload the changes in the container
      - ./frontend/src:/usr/src/app/src # write these as ./<path to folder>:/<path to folder in container>
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5555 # this defines the URL the frontend makes requests to

  init_test:
    build:
      context: ./backend/web
    command: ["./init_test"]
    depends_on:
      user_srv:
        condition: service_started
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      web:
        condition: service_started
    environment:
      DATABASE_DSN: "root:root@tcp(mysql:3306)/capstone?charset=utf8mb4&parseTime=True&loc=Local"
    restart: on-failure

volumes:
  mysql-data:
